### ISSUE TITLE
jclic.js not working using Safari in iOS

### ISSUE THREAD

**Issue by MarcCeleiro** [projectestac/jclic.js#17]
jclic.js is not working when I use Safari in any iOS device. This means that if I try to put a JClic activity inside my iOS app or I open within the Safari browser, the screen is always blank. I need to use other browsers like Chrome, but Safari is the default one and I cannot change it :(

**Comment by frncesc** [comment]
Tested with different iPhone and iPad models and Safari versions, using real devices in [Browserstack](https://browserstack.com) against the same JClic project:

|Model                |Safari version |Result|
|----------------------|-------------------|---------|
|iPhone XS Max | 12                  | ✔     |
|iPhone X           | 11                   | ✔     |
|iPhone 7           | 10                   | ✔     |
|iPhone 6S Plus |  9                   | ✔     |
|iPhone 6 Plus   |  8                    | ✔     |
|iPad Pro 12.9    | 11                   | ✔     |
|iPad Air 2          | 8                     | ✔     |
|iPad Air             | 7                     | ❌    |

Safari V7 halts with an "Invalid state error"  (maybe because it's out of the scope of [babel preset-env](https://babeljs.io/docs/en/babel-preset-env)?)

In all cases, the site certificate of https://clic.xtec.cat is not recognized by iOS and must be manually accepted. This is because our server certificate is issued by "Agència Catalana de Certificació", an AC that is not currently recognized by iOS (see [this document](https://www.aoc.cat/knowledge-base/manual-dinstal%C2%B7lacio-de-certificat-en-programari-ios-dispositius-mobils-iphoneipad/?dms3override=15) for directions about how to install the root certificate on your system)

What device model, iOS version and Safari version are you using?

**Comment by MarcCeleiro** [comment]
After reviewing the security parameters (to see if there were any problem with the certificate), now works well. Sorry for the inconvenience!

**Comment by frncesc** [comment]
OK 👍

If you have JClic projects hosted in your own server, you can pick `jclic.min.js` from a different CDN in order to avoid problems with our CA root certificate. Just edit the `index.html` of each project and replace the reference to `https://clic.xtec.cat/dist/jclic.js/jclic.min.js` with one of these:
- `https://unpkg.com/jclic/dist/jclic.min.js`
- `https://cdn.jsdelivr.net/npm/jclic@latest/dist/jclic.min.js`
- `https://cdnjs.cloudflare.com/ajax/libs/jclic.js/1.1.9/jclic.min.js` (in this case, remember to update the version number as new versions are released)
