### ISSUE TITLE
LIbrery version  1.1.12 crashes on Safari

### ISSUE THREAD

**Issue by jaumemoron** [projectestac/jclic.js#18]
Hi

JClic projects crashes on Safari browser, The error is below:

_TypeError: 'undefined' is not a constructor (evaluating 'new Audio(n)')_

Error is localized on the following code

`if (Utils.startsWith(fileName, 'data:'))
                                    this.audio = new Audio(fileName);`

This error cause that JClic librarry does not supported by Safari browser (mobile and laptops devices)

Thanks

**Comment by frncesc** [comment]
I'm unable to reproduce the error.

I have tested successfully tested the [demo project](https://clic.xtec.cat/demo/jclic.js/index.html) on [BrowserStack](https://www.browserstack.com/) on:

- iOS v11 (iPad 5th): Errors in Safari related to the lack of [AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext), but the app is usable. OK in Chrome.
- iOS v12 (iPad Pro): OK in Safari and Chrome
- iOS v13 (iPad 7th): OK in Safari and Chrome 

A warning about the server certificate is shown due to Apple's lack of trust in the certificate authority used by our host (EC-ACC), but it can be easily passed by accepting "unsafe" navigation.

Please provide mor inormation about:

- The device where this error was observed
- The operating system type (iOS, MacOS) and version
- The URL where the error has been detected
- Please, check the same URL with Chrome

Thank you!

**Comment by jaumemoron** [comment]
Hi.

A little example of project that does'nt run on Safari, deployed on xtec site:
url: https://clic.xtec.cat/projects/jmiro2/jclic.js/index.html
Safari version: 5.1.7
OS: Windows 10
You will see that jclic project is not shown (a blank page is shown) and the following error is shown on the Safari  debug console:

`TypeError: 'undefined' is not a constructor (evaluating 'new Audio(n)')`

Projects based on this xtec project has the same beahavior: on pc and iphone.

Regards

**Comment by frncesc** [comment]
Safari for Windows was [discontinued in 2012](https://en.wikipedia.org/wiki/Safari_version_history#Safari_5_2). It does not support the HTML5 standards!

Please use an updated version of any modern browser, like Firefox, Chrome or Edge. You can also use an updated version of Safari, but only on non-discontinued iOS and MacOS devices.
